### ISSUE TITLE
Allow customization of data.num_nodes

### ISSUE THREAD

**Issue by ostrokach** [rusty1s/pytorch_geometric#190] opened 2019-04-05 22:13 UTC
## To Reproduce

I have a dataset of `Data` objects that have `y`, `edge_index`, and `edge_attr` attributes but no `x` attribute (the `x` is generated on the fly by randomly removing some values in `y`). When I train a network using batches of data generated using `DataLoader` with `batch_size > 1`, I observe terrible performance. Reducing `batch_size` to 1 results in better performance.

Long story short, after two days of debugging I realize that `torch_geometric` is incorrectly guessing the number of nodes in my graphs (since they may not be fully connected), resulting in shifted adjacency matrices for all subsequent graphs in the batch.

## Expected behavior

In the very least, a warning should be emitted when  we are "guessing" the number of nodes in a graph. Also, `y` should potentially also be used to infer the number of nodes in a graph?

**Comment by rusty1s** [comment] 2019-04-05 22:23
Hi, I'm really sorry for your lost days regarding this issue. I'm not quite sure what causes the performance issue, since "guessing" refers to a simple `edge_index.max()` call (which should by no means result in significant performance decreases). We could use `y` to infer the number of nodes, but this could potentially result in unexpected behaviour since we declare no constraints on the shape of `y`.

I think you have two simple ways to fix your issue:
1. Inherit from `Data` and create your own data object where you redefine `num_nodes`.
2. Add a small placeholder tensor to `data.x` with correct shape, *e.g.*, `data.x = torch.zeros(num_nodes, dtype=torch.uint8)`

However, can you elaborate a little more why PyG is wrongly guessing the number of nodes?

**Comment by rusty1s** [comment] 2019-04-16 06:06
I'm closing this due to inactivity. Feel free to reopen.

**Comment by ostrokach** [comment] 2019-04-16 22:03
Sorry for the delay in responding.

I have brewed on this issue for a bit, and I guess it is more of a feature request than a bug report. PyG provides an awesome API for working with graph data, and it has greatly simplified my workflow. However, I believe that in some cases it provides a bit too much "magic" rather than following the "explicit is better than implicit" mantra. An example of this, which in my case led to a hard-to-find bug, is [`return maybe_num_nodes(self.edge_index)`](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/data/data.py#L131) inside the `Data.num_nodes` property. Guessing the number of nodes in a graph from the `edge_index` vector is not going to be correct in 100% of the cases (this is why you appropriately named the function as `maybe_num_nodes`). The amount of time this function saves in 99% of the cases is more than offset by the amount of time it takes to find the cause of obscure bugs in 1% of cases. In my case, the discrepancy between `maybe_num_nodes` and the actual number of nodes led to incorrect edge information for all but the first datapoint in `Batch` objects generated using the `DataLoader`.

My personal opinion is that it should be mandatory to overwrite the `Data.num_nodes` property for data points without an `x` attribute. Maybe in the documentation there could be an example of how to do this with `return maybe_num_nodes(self.edge_index)`.

Anyway, this is just my 2c. Feel free to ignore, as I am sure that you have more important things to work on, and this is not a "bug" as long as someone is aware of the implementation details.

**Comment by rusty1s** [comment] 2019-04-16 22:21
Mh ok, I see what you mean there. We could make `num_nodes` an actual property that users can override. I leave this issue open until I come up with an elegant way to fix this. Thank you so much for your feedback.

**Comment by rusty1s** [comment] 2019-04-18 07:16
Hi, I added this functionality to current master. You can now set `data.num_nodes = ...` explicitly, and are given a warning if PyG defaults to "guessing" based on edge indices. I'm closing this for now. Feel free to reopen if you encounter any issues. Thanks again!

**Closed by rusty1s** 2019-04-18 07:16 UTC
Labels: request

**Comment by ostrokach** [comment] 2019-04-18 15:03
Awesome, thanks!
