### ISSUE TITLE
torch-cluster has no CUDA version, as mentioned in the installation instructions of PyG

### ISSUE THREAD

**Issue by douglasrizzo** [rusty1s/pytorch_geometric#1031] opened 2020-03-16 11:47 UTC
## 📚 Installation

The installation instructions mention that, in order to install `torch-cluster`, we need to ask for `torch-cluster==latest+${CUDA}`, but `torch-cluster` has no such version (e.g. with `cu92`, `cu100` or `cu101`). In torch-cluster's repo, the installation instructions are simply to run `pip install torch-cluster`, without an explicit CUDA version.

In short, I believe the command to install torch-cluster in the pytorch-geometric README may be wrong.

## Environment

* OS: Manjaro Linux 19.0.2 Kyria
* Python version: 3.7.6
* PyTorch version: 1.4.0
* CUDA/cuDNN version: 10.1/7.6.5
* GCC version: 8.3.0
* How did you try to install PyTorch Geometric and its extensions (pip, source): pip
* Any other relevant information:

## Checklist

- [X] I followed the installation guide.
- [ ] I cannot find my error message in the FAQ.
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [ ] I have cloned the repository and tried a manual installation from source.
- [ ] I do have multiple CUDA versions on my machine.
- [ ] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

**Comment by rusty1s** [comment] 2020-03-16 13:34
Yeah, I am aware of this. Try https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0.html in the meantime.

**Comment by mwussow** [comment] 2020-03-16 16:45
It seems to me as though **this version of torch-cluster is not running as intended**.
I successfully installed it with `pip install torch-cluster==latest+cu100 -f https://s3.eu-central-1.amazonaws.com/pytorch-geometric.com/whl/torch-1.4.0.html` and ran `mnist_graclus.py` from the examples folder without running into an error. However, it seems like it ran into an infinite loop, since the **first epoch did not complete within 60min of training on a Nvidia Quadro P5000**.

**Comment by rusty1s** [comment] 2020-03-16 18:22
Ok, let me look into this.

**Comment by rusty1s** [comment] 2020-03-17 07:05
Fixed in v1.5.2.

**Closed by rusty1s** 2020-03-17 07:05 UTC
