### ISSUE TITLE
Graph Convolution with Graphs consisting of only a single isolated Node returns strange values

### ISSUE THREAD

**Issue by evakrowarska** [rusty1s/pytorch_geometric#1129] opened 2020-04-16 08:09 UTC
When I am doing a graph convolution over graphs each consisting of a single isolated node, what should be the result? 
To my understanding it should not change the value of node `x_i` at all, since there is no `x_j` to convolve with.

But when I try it out, I get very huge or very small numbers, such that after a few batches I have `nan values` in my forward pass. 

What I have done:
**1)** 
```
self.conv = EdgeConv(MLP([2 * 64, 64]), aggr)
out = self.conv(torch.zeros([1, 64], dtype=torch.float32), torch.zeros([2, 0], dtype=torch.int64))
```

this gives the result for out:

```
tensor([[ 0.0000e+00,  0.0000e+00,  3.7835e-43,  0.0000e+00, -3.0873e+26,
          3.0778e-41, -3.0873e+26,  3.0778e-41,  5.3866e-42,  0.0000e+00,
          5.5421e-42,  0.0000e+00, -2.7435e+26,  3.0778e-41, -2.7435e+26,
          3.0778e-41, -2.7435e+26,  3.0778e-41, -3.0102e+26,  3.0778e-41,
         -2.7436e+26,  3.0778e-41,  8.6102e+22,  4.5563e-41,  1.7937e-43,
          0.0000e+00,  1.7937e-43,  0.0000e+00, -2.7439e+26,  3.0778e-41,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  4.0217e-43,
          0.0000e+00, -3.0873e+26,  3.0778e-41, -3.0873e+26,  3.0778e-41,
          5.4889e-42,  0.0000e+00,  5.5421e-42,  0.0000e+00, -2.7436e+26,
          3.0778e-41, -2.7436e+26,  3.0778e-41, -2.7436e+26,  3.0778e-41,
         -2.7439e+26,  3.0778e-41, -2.7436e+26,  3.0778e-41, -2.7435e+26,
          3.0778e-41,  3.5873e-43,  0.0000e+00,  1.7937e-43,  0.0000e+00,
         -2.7088e+26,  3.0778e-41,  0.0000e+00,  0.0000e+00]],
       grad_fn=<CppNode<ScatterMax>>)
```
**2)** But if I do: 
```
my_edge_index = torch.tensor([[0, 0],
                           [0, 0]], dtype=torch.long)
out = self.conv(torch.zeros([1, 64], dtype=torch.float32), my_edge_index)
```
this gives the result for out:

```
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       grad_fn=<CppNode<ScatterMax>>)
```

**Question**: Can you explain the result for case 1)? I would have expected the output for case 2) in case 1), as well. 
I feel like adding self loops to isolated nodes does distort the model a bit. Is there a way of keeping isolated without adding self-loops to them?

I had a guess, that the biases could produce that issue. Unfortunately, turning them off did not change the result.

Thank you in advance!

Note that: 

```
def MLP(channels, batch_norm=True):
    return Sequential(*[
        Sequential(Linear(channels[i - 1], channels[i], bias=False), ReLU(), BatchNorm1d(channels[i]))
        for i in range(1, len(channels))
    ])
```

**Comment by rusty1s** [comment] 2020-04-16 08:32
That seems to be a problem with the CPU version of `scatter_max`. I will fix it.

**Comment by rusty1s** [comment] 2020-04-16 08:53
It is fixed in `torch-scatter` master now. Note that this error only occured in case `index.numel()` (which almost never happens), I will wait before drafting a new release.

**Comment by evakrowarska** [comment] 2020-04-16 08:54
I have changed my code to :

```
out = self.conv(torch.zeros([1, 64], dtype=torch.float32, device='cuda'), torch.zeros([2, 0], dtype=torch.int64, device='cuda'))
print("no edges")
print(out)
my_edge_index = torch.tensor([[0, 0],
                                      [0, 0]], dtype=torch.long, device='cuda')
out = self.conv(torch.zeros([1, 64], dtype=torch.float32, device='cuda'), my_edge_index)
print("with self-loops")
print(out)
```

and I am getting a similiar output. But this time the convolution with self loops on an isolated node does not result in a tensor full of zeros:

```
no edges
tensor([[ 3.0829e-44,  0.0000e+00, -0.0000e+00,  1.3370e+00, -2.0000e+00,
          9.8786e-01,  2.0000e+00,  1.3603e+00,  3.6893e+19,  1.3830e+00,
         -0.0000e+00,  1.5303e+00,  3.6893e+19,  1.5467e+00, -2.0000e+00,
          1.5800e+00, -2.0000e+00,  1.4424e+00,  1.0842e-19,  1.1315e+00,
         -3.6893e+19,  1.0623e+00, -2.0000e+00,  1.0898e+00,  3.6893e+19,
          1.0739e+00, -3.6893e+19,  1.4191e+00, -0.0000e+00,  1.0018e+00,
         -0.0000e+00,  1.5033e+00,  2.0000e+00,  1.4457e+00, -1.0842e-19,
          1.5423e+00, -2.0000e+00,  1.3161e+00, -2.0000e+00,  8.1336e-01,
         -0.0000e+00,  1.5678e+00,  3.6893e+19,  1.5304e+00,  3.6893e+19,
          1.3279e+00,  2.0000e+00,  1.5950e+00,  3.6893e+19,  1.2405e+00,
          2.0000e+00,  1.4522e+00,  3.6893e+19,  1.5333e+00,  3.6893e+19,
          1.5563e+00, -1.0842e-19,  1.5157e+00,  0.0000e+00,  1.2951e+00,
          3.6893e+19,  1.5074e+00,  2.0000e+00,  1.1165e+00]], device='cuda:0',
       grad_fn=<CppNode<ScatterMax>>)
with self-loops
tensor([[-0.0938,  0.0538,  0.0081, -0.0585, -0.0657, -0.1549, -0.1714, -0.2039,
          0.0974,  0.0179,  0.0118, -0.0118, -0.0115, -0.0844, -0.0070,  0.1286,
         -0.0972,  0.1681,  0.0487,  0.0012, -0.1924, -0.1545,  0.0513,  0.2215,
         -0.0303, -0.0999,  0.1597, -0.1820, -0.1396,  0.0443, -0.1324, -0.0145,
         -0.0725, -0.0930,  0.0857, -0.1337, -0.1810,  0.0055,  0.0140, -0.1252,
         -0.1317, -0.1966,  0.0961,  0.0143, -0.0963,  0.1164, -0.3062,  0.0841,
         -0.0348, -0.1087,  0.0756,  0.0689,  0.0186, -0.0889, -0.0532,  0.0719,
          0.0068,  0.1591,  0.0591, -0.0311,  0.0811,  0.0197,  0.1104, -0.0884]],
       device='cuda:0', grad_fn=<CppNode<ScatterMax>>)
```

Is this related to the CPU problem you have mentioned?
And thank you for taking care and fixing the bug. I really appreciate that!

**Closed by rusty1s** 2020-04-16 08:53 UTC

**Comment by rusty1s** [comment] 2020-04-16 08:55
No, it was not related to CPU, but it is definitely fixed now :)

**Comment by evakrowarska** [comment] 2020-04-16 10:32
Thank you! :) 
I have cloned your repo` torch-scatter` and then I executed `python setup.py develop`.
Now, with the following code: 

```
out = self.conv(torch.zeros([1, 64], dtype=torch.float32, device='cuda'), torch.zeros([2, 0], dtype=torch.int64, device='cuda'))
print("no edges")
print(out)
my_edge_index = torch.tensor([[0, 0],
                                      [0, 0]], dtype=torch.long, device='cuda')
out = self.conv(torch.zeros([1, 64], dtype=torch.float32, device='cuda'), my_edge_index)
print("with self-loops")
print(out)
```

I get different results on `CUDA` and `CPU`. 
Output for `CUDA`: 

```
no edges
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       device='cuda:0', grad_fn=<CppNode<ScatterMax>>)
with self-loops
tensor([[-9.5755e-03,  1.4795e-02, -5.2888e-03, -3.4876e-03, -1.7672e-02,
         -2.9582e-02,  7.3427e-03, -5.4218e-03,  8.7945e-03, -9.2727e-03,
         -1.5711e-02,  2.9520e-02,  1.2327e-02,  3.7727e-02,  3.9715e-03,
         -2.2232e-02, -1.2661e-02, -2.0665e-02, -4.3999e-05, -2.1708e-02,
          2.1919e-02,  1.6696e-02,  4.4743e-03, -7.3992e-03, -6.2204e-03,
         -1.1097e-02,  1.2566e-02, -6.0008e-03,  3.0477e-02,  9.6513e-04,
          3.0687e-02, -9.1224e-03, -1.6812e-02, -5.8893e-03, -5.6220e-03,
         -2.9202e-03, -3.3969e-03,  1.8205e-02,  6.8784e-03,  2.8377e-02,
          1.1642e-02,  1.2662e-02,  8.7714e-03,  2.1418e-02, -1.2092e-02,
          2.4726e-02,  2.4415e-02,  1.6664e-02,  2.7586e-02,  7.5546e-03,
         -3.6779e-03, -2.1891e-03, -1.1906e-02, -5.0221e-04, -1.1857e-02,
          8.7585e-03, -2.2918e-02, -1.1328e-02, -1.7817e-02, -1.1924e-02,
         -1.1879e-02, -8.9144e-04,  8.8955e-03,  2.8541e-02]], device='cuda:0',
       grad_fn=<CppNode<ScatterMax>>)
```

Output for `CPU`: 
```

no edges
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       grad_fn=<CppNode<ScatterMax>>)
with self-loops
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       grad_fn=<CppNode<ScatterMax>>)
```

Is that an setup problem on my computer? 
Or does the distinction of `CUDA` and `CPU` operate differently?

I have expected only zero-tensors for all cases as output. Is that a correct assumption?

**Comment by rusty1s** [comment] 2020-04-16 10:41
I can not reproduce this. It's all zeros for me (without bias).

**Comment by rusty1s** [comment] 2020-04-16 10:52
Can you send me your complete script to reproduce this?

**Comment by evakrowarska** [comment] 2020-04-17 09:45
I have found out, that running the code on the cluster (no matter if i use a gpu or not) produces the following output: 

```
no edges
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       device='cuda:0', grad_fn=<CppNode<ScatterMax>>)
with self-loops
tensor([[-9.5755e-03,  1.4795e-02, -5.2888e-03, -3.4876e-03, -1.7672e-02,
         -2.9582e-02,  7.3427e-03, -5.4218e-03,  8.7945e-03, -9.2727e-03,
         -1.5711e-02,  2.9520e-02,  1.2327e-02,  3.7727e-02,  3.9715e-03,
         -2.2232e-02, -1.2661e-02, -2.0665e-02, -4.3999e-05, -2.1708e-02,
          2.1919e-02,  1.6696e-02,  4.4743e-03, -7.3992e-03, -6.2204e-03,
         -1.1097e-02,  1.2566e-02, -6.0008e-03,  3.0477e-02,  9.6513e-04,
          3.0687e-02, -9.1224e-03, -1.6812e-02, -5.8893e-03, -5.6220e-03,
         -2.9202e-03, -3.3969e-03,  1.8205e-02,  6.8784e-03,  2.8377e-02,
          1.1642e-02,  1.2662e-02,  8.7714e-03,  2.1418e-02, -1.2092e-02,
          2.4726e-02,  2.4415e-02,  1.6664e-02,  2.7586e-02,  7.5546e-03,
         -3.6779e-03, -2.1891e-03, -1.1906e-02, -5.0221e-04, -1.1857e-02,
          8.7585e-03, -2.2918e-02, -1.1328e-02, -1.7817e-02, -1.1924e-02,
         -1.1879e-02, -8.9144e-04,  8.8955e-03,  2.8541e-02]], device='cuda:0',
       grad_fn=<CppNode<ScatterMax>>)
```

on my notebook (cpu-only):
```
no edges
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       grad_fn=<CppNode<ScatterMax>>)
with self-loops
tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],
       grad_fn=<CppNode<ScatterMax>>)
```

So it seems like the remaining issue is a setup problem and no more a library bug.
I would really appreciate if you could still help me solving the issue. 

On the cluster environment, I have removed all the packages via pip uninstall that are related to pytorch geometric. Then I have created a local folder, cloned each repository into it and executed python setupt.py develop, for each of them. 
So, on the cluster I have installed at the moment: 

```
torch                 1.4.0               
torch-cluster         1.5.4      
torch-geometric       1.4.3              
torch-scatter         2.0.4               
torch-sparse          0.6.2            
torch-spline-conv     1.2.0               
torchvision           0.5.0  
```

On my notebook: 

```
torch                  1.4.0               
torch-cluster          1.5.3               
torch-geometric        1.4.3               
torch-scatter          2.0.4               
torch-sparse           0.6.1               
torch-spline-conv      1.2.0               
torchvision            0.5.0   
```

The following code to (hopefully) reproduce the issue:

```
import torch
from torch.nn import Sequential, Linear, ReLU, BatchNorm1d, Dropout
from torch_geometric.nn import EdgeConv, DynamicEdgeConv, global_max_pool, max_pool, knn_graph
from torch_geometric.data import Data

def MLP(channels, batch_norm=True):
    return Sequential(*[
        Sequential(Linear(channels[i - 1], channels[i], bias=False), ReLU(), BatchNorm1d(channels[i]))
        for i in range(1, len(channels))
    ])

class Network(torch.nn.Module):
    def __init__(self, device):
        super().__init__()
        self.conv2 = EdgeConv(MLP([2 * 64, 64]), 'max')
        self.device = device

    def forward(self, data):

        out = self.conv2(torch.zeros([1, 64], dtype=torch.float32, device=self.device), torch.zeros([2, 0], dtype=torch.int64, device=self.device))
        print("no edges")
        print(out)
        my_edge_index = torch.tensor([[0, 0],
                                      [0, 0]], dtype=torch.long, device=self.device)
        out = self.conv2(torch.zeros([1, 64], dtype=torch.float32, device=self.device), my_edge_index)
        print("with self-loops")
        print(out)

        return out

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Network(device=device).to(device)
print(device)
data = Data(x=None, edge_index=None).to(device)
out = model(data)

```

Thank you in advance!

**Comment by rusty1s** [comment] 2020-04-17 11:22
Can you run the test suite of `torch-scatter` and see if that succeeds?

**Comment by evakrowarska** [comment] 2020-04-17 13:43
The tests succeed. 
But before I had somewhere (I forgot when) that cuda versions of the packages did not match. 

So I uninstalled all pytorch geometric related packages again. 
Then, I installed all by: 
```

$ pip install torch-scatter==latest+${CUDA} -f https://pytorch-geometric.com/whl/torch-1.4.0.html --no-cache-dir
$ pip install torch-sparse==latest+${CUDA} -f https://pytorch-geometric.com/whl/torch-1.4.0.html --no-cache-dir

$ pip install torch-cluster==latest+${CUDA} -f https://pytorch-geometric.com/whl/torch-1.4.0.html --no-cache-dir

$ pip install torch-spline-conv==latest+${CUDA} -f https://pytorch-geometric.com/whl/torch-1.4.0.html --no-cache-dir

$ pip install torch-geometric --no-cache-dir

```

But then I got the original behavior, that turned out to be the bug, you mentioned before. 
So I thought, that these wheel are just the latest release, but not cutting edge from source. 

So I reinstalled torch-scatter from source by executing python setup.py develop again. 

It seems that it works as expected now!

**Just for my interest**: Where can I find the installation options, e. g. cuda version if I clone the master branch and install from source?
Something like:` python setup.py cu101` (in fact, this one did not work for me)?

**Comment by rusty1s** [comment] 2020-04-17 15:27
Cool! For installation from source, it picks the version that it founds in `$CUDA_HOME`.
