### ISSUE TITLE
Issue while using tensorboard with geneipath model

### ISSUE THREAD

**Issue by nikitamehrotra12** [rusty1s/pytorch_geometric#895] opened 2020-01-10 13:31 UTC
## 🐛 Bug

I am using geneipath graph conv model with some different data set. I am trying to log the model graph and train/test accuracy. But I am getting an error on **add_graph** function from PyTorch.

Error is: **RuntimeError: in place ScatterMax not supported in the JIT**

![Screenshot (3)](https://user-images.githubusercontent.com/20640205/72156144-c89f6d80-33da-11ea-95b6-bcf257bfc305.png)

## Expected behavior

Add_graph should log the training graph at the specified logdir, that can be visualised later in tensorboard.

## Environment

* OS: Ubuntu
* Python version: 3.7.3
* PyTorch version: 1.3.1
* CUDA/cuDNN version: 10.0.130
* GCC version: 7.4.0
* Any other relevant information:

**Comment by rusty1s** [comment] 2020-01-13 15:42
The problem is that the JIT can not handle our own kernel functions. I will look into how this can be fixed :)

**Comment by tornadomeet** [comment] 2020-06-10 03:30
Any update? @rusty1s

**Comment by rusty1s** [comment] 2020-06-10 04:14
That is supported by now :) I just forgot to close this.

**Closed by rusty1s** 2020-06-10 04:14 UTC
Labels: request

**Comment by tornadomeet** [comment] 2020-06-10 05:56
thanks @rusty1s 
Would you show which commit or pr fix this problem? i searched but not find.

**Comment by rusty1s** [comment] 2020-06-10 05:57
See https://github.com/rusty1s/pytorch_scatter/releases/tag/2.0.2.

**Comment by tornadomeet** [comment] 2020-06-10 06:03
great  thanks!
