### ISSUE TITLE
Issue reproducing the results of the original ecc implementation. Pooling layer and conv layer are giving different results of the original implementation

### ISSUE THREAD

**Issue by dhorka** [rusty1s/pytorch_geometric#331] opened 2019-05-22 10:55 UTC
As I mentioned in #319  I have problems to reproduce the [ecc implemenation](https://github.com/mys007/ecc) using pytorch_geometric. I found some differences between the results obtained, first one is that the results of both convolution operations using the same weights have different results. Moreover, the results of the pooling layers are also different. 

I created a test that checks this things. Basically, the scripts load the same weights to both implementations. These weights are obtained from train a network using the ecc_implementation. Below you can see the output of my test.

```
ECC Weights and PyGeometric weights are equal: True #I am only doing a re-check in order to be sure that both weights are equal before to load to the models.
Loading weights 
Starting validation:
ecc features conv1:  (997, 16) #Shape of the output of first conv in ecc implementation
pygeometric features conv1:  (997, 16) #Shape of the output of first conv in pygeometric implementation
Max difference between features of first conv 2.549824
Output of ecc pooling:  (398, 32)
Output of PyGeometric pooling:  (385, 32)
Pygeomtric Acc:  41.51982378854625  Ecc accuracy:  63.65638766519823
Pygeomtric Loss:  2.435516586519023  Ecc Loss:  0.9878960176974138
```
As you can observe this difference has an impact to the accuracy using the same weights. You can find the source code [here](https://github.com/dhorka/eccvspygeometric.git). One important thing, the data used for this tests is obtained from the original code of the ecc.

**Comment by rusty1s** [comment] 2019-05-22 15:58
I will look into it. You could do me a huge favor by implementing a simple example to reproduce this. The current codebase is quite hard to analyze.

**Comment by dhorka** [comment] 2019-05-23 02:27
The main code reproduce the output that I posted. Is it what you want? Maybe I can put some comments on the main code to make eassy the analysis.

**Comment by rusty1s** [comment] 2019-05-23 03:27
Well, I haven‘t looked at it in more detail, but it would be nice to just have a basic script that compares the output of just the convolution on a mini example like a triangle graph.

**Comment by dhorka** [comment] 2019-05-23 05:05
At this moment, the comparison it is done with a modelnet point cloud. The think is, that the structure of data used in the original ecc it is not trivial... The script I provided, compares the output of the first convolution of both implementation and also compares the output of the first max pooling. If you really need, I can try  to do it.

One important thing that I forgot to mention is, that you need to compile from source open3d and pytorch to avoid run time problems. As it is described [here](https://github.com/pytorch/pytorch/issues/19739). Moreover, the code provided is adapted to pytorch 1.1.

**Comment by yorard123** [comment] 2019-06-04 05:35
Is there any news on this topic? I am facing the same issue. The same ecc architecture it is giving me less accuracy using the pyg implementation than the original implementation...

**Comment by rusty1s** [comment] 2019-06-04 07:33
Actually, the installation of `open3d` is a real damper. Looking alone at the source code, I see no reason for the convolutions to perform differently, given the same input. Are you sure the input graphs are identically? Can you ensure that the [ecc weights](https://github.com/dhorka/eccvspygeometric/blob/master/ecc/GraphConvModule.py#L172) and the `self.conv1.nn(data.edge_attr)` call from [PyTorch Geometric](https://github.com/rusty1s/pytorch_geometric/blob/master/torch_geometric/nn/conv/nn_conv.py#L73) are the same?

**Comment by dhorka** [comment] 2019-06-04 10:45
> Actually, the installation of open3d in combination with torch is a real damper and I haven't had time to install both from source yet.

As far as I remember I think building from source pytorch and installing from pip open3d is enough.

> Looking alone at the source code, I see no reason for the convolutions to perform differently, given the same input. Are you sure the input graphs are identically? 

The parameters of the knn, edge attr and so on are the same. If the graphs are not the same I not checked to be honest, but if it is not the same, then there is a bug in the graph creation? 

> Can you ensure that the ecc weights and the self.conv1.nn(data.edge_attr) call from PyTorch Geometric are the same (w.r.t. permutation-invariance for a given neighborhood)?

It doesn't matter the order right? Or Am I wrong?

At the end, if you train a network using ecc implementation and pyg implementation the first one obtain always better results than the first one.  O observed this on some datasets. Using the same seed, same parameters etc to obtain the results. As a remember this issue is the second part of this one: #319

**Comment by rusty1s** [comment] 2019-06-04 10:53
Well, you said the output of the first convolution yields different results, so it would be reasonable to check at which call the results start to differ. For example, `knn` graph generation is not necessarily deterministic (considering there are points with the same distance to other points). In addition, the implementations might differ in the `k` in `knn` producing `k+1` or `k` neighbors when adding self-loops. I would be very pleased if you could verify that, so I do not need to recompile both libs from source.

We can look at the different voxel grid implementations afterwards.

**Comment by rusty1s** [comment] 2019-06-04 14:07
I managed to run it on my machine. A first analysis already yields some differences in the input representation:
* Cartesian coordinates are inverted in the ECC implementation
* There is a weird `unique_rows` call in `ecc/utils.py` which changes the underlying `knn` graph structure
I will dig deeper. However, the `knn` graph generation yields equivalent graphs.

**Comment by rusty1s** [comment] 2019-06-04 16:01
After more investigation,  `edgecompaction=0` for the ECC model and `conv1.flow = 'target_to_source` for the PyG model will yield equivalent results. This indicates that we need to swap the `row` and `col` vectors for the `knn` generation when using `flow='source_to_target`.

**Comment by rusty1s** [comment] 2019-06-04 16:24
For the voxel grid pooling, the implementations use different starting vectors for voxels. PyG starts its voxels at `data.pos.min(dim=0)` by default (which is `(0,0,0)` for ModelNet), but I am not sure what `open3d` is using. The documentation does not say a word about this.

**Comment by rusty1s** [comment] 2019-06-04 16:46
So either transpose your edge indices in PyG or use a different flow direction. Doing either of this should yield similar results as the official implementation. I will add a remark to the knn documentation.

**Comment by dhorka** [comment] 2019-06-04 17:16
Hi,
I was checking to change the flow of nnconv and I observed that the current implementation is not mapping the flow parameter of the message class. But, I created my custom nnconv adding tflow='target_to_source'. I re-run the experiment but unfortunatly I am not obtaining the same result after the first conv layer. Am I missing something?

**Comment by dhorka** [comment] 2019-06-04 17:24
Solved, I forgot to adapt the cartesian coordinates. At this moment I am obtaining a difference between both implementations of: 4.7683716e-07 I think this is expected. I will check with more data, and I will come back. In the meantime can be possible to add a flag to the knn method that transposes the row and col? Then it will be possible to use the default cartesian method, right?

The new values of accuracy and loss using these changes are:

Pygeomtric Acc:  61.89427312775331  Ecc accuracy:  63.65638766519823
Pygeomtric Loss:  1.0270526386830254  Ecc Loss:  0.9878960071943925

I suppose this difference it is due to the difference between the implementation of open3d and pygeomettric, can be?

**Comment by rusty1s** [comment] 2019-06-04 17:45
Yes, there are different outputs of the voxel grid implementations due to different starting vectors. I will investigate that further.

The flag on knn is a good idea. Will do this. Then you can use the right Cartesian, yes.

**Comment by dhorka** [comment] 2019-06-04 18:01
> Yes, there are different outputs of the voxel grid implementations due to different starting vectors. I will investigate that further.

I was checking the code of open3d, I need to check in more detail but I think this is the file that we need to check https://github.com/intel-isl/Open3D/blob/20d8cc6ae41ed7f74d7bd374b70eef8005e45b4d/src/Open3D/Geometry/DownSample.cpp#L247

> The flag on knn is a good idea. Will do this. Then you can use the right Cartesian, yes. 
Thanks! 

> In addition, it is reasonable to pass kwargs to the Message Passing class.
I'm agree with that

**Comment by rusty1s** [comment] 2019-06-04 18:12
```python
Eigen::Vector3d voxel_min_bound = input.GetMinBound() - voxel_size3 * 0.5;
Eigen::Vector3d voxel_max_bound = input.GetMaxBound() + voxel_size3 * 0.5;
```
So instead of using `start=pos.min(dim=0)[0]` it uses `start=pos.min(dim=0)[0] - size * 0.5`. In your case, a simple `start=-1.25` should do the trick :)

**Comment by dhorka** [comment] 2019-06-04 18:25
> In your case, a simple start=-1.25 should do the trick :)
Well, only in the first layer. I will check to add both start and end in the same way that it is done in open3d and I will come back with the result. Tomorrow morning I will tell you the results :) (I do not have gpu avaible at this moment) Thank you so much for your help!

**Comment by dhorka** [comment] 2019-06-04 18:39
I was checking in cpu, and I have this error when I use this: `start=pos.min(dim=0)[0] - size * 0.5`
`TypeError: add(): argument 'other' (position 1) must be Tensor, not list
`
It seems like I can not pass a tensor as a parameter.

**Comment by rusty1s** [comment] 2019-06-04 18:53
Use `pos.min(dim=0)[0].tolist()` instead. Will fix in master.

**Comment by rusty1s** [comment] 2019-06-04 18:59
Fixed in master. You can now pass `flow` to any `MessagePassing` operator. In addition, `knn_graph` and `torch_geometric.transforms.KNNGraph` now have `flow` arguments with default `source_to_target`. You need to update `torch-cluster` to `1.4.1`. Please check if everything works as expected. I will craft a new PyG release if everything works :)

**Comment by dhorka** [comment] 2019-06-04 19:07
Yeps, tomorrow I will update my setup and I will check all. I achieved to execute the voxel_grid with the new start and end and these are the results:

```
ecc features conv3:  (398, 32)
pygeometric features conv3:  (398, 32)
Max difference between features of  conv3: 8.112797
Pygeomtric Acc:  62.334801762114544  Ecc accuracy:  63.65638766519823
Pygeomtric Loss:  1.0285567773858866  Ecc Loss:  0.9878960071943925
```
Conv3 is the convolution after the first max pooling using voxel_grid. We are close! Now there are the same number of points! But the difference it is high in this layer.  Tomorrow I will update my setup in order to use the new updates, and I will modify the code to obtain the output of the first max pooling in order to compare the results.

**Comment by rusty1s** [comment] 2019-06-04 19:18
Well, checking difference between feature maps *after* pooling is not well-defined, because ordering of nodes may be different. We need to first sort point clouds based on their position (in both implementations) before taking the difference.

**Comment by dhorka** [comment] 2019-06-05 05:00
> Well, checking difference between feature maps after pooling is not well-defined, because ordering of nodes may be different. We need to first sort point clouds based on their position (in both implementations) before taking the difference.

You are right! Then maybe it is only a slightly different due to the numerical instability in gpus, right? But I suppose we need to checked to be sure and close properly the issue.

I updated pygeometric and torch-cluster and I think there is an error. I think target_to_source and source_to_target are inverted.  The first check that I done is execute the previous code with the new version, using the adapted cartesian and with the nnconv flow changed to target_to_source. By default knn has flow=source_to_target that I suppose it is the same than the previous version. Using that I am obtaining different results (bad ones) If I change the knn to target_to_source. Then I am obtaining the same results than with the previous versions.  Moreover using default cartesian coordinates, nnconv with source_to_target and knn target_to_source it is obtaining bad results, but If i change knn to source_to_target it is working again. I think source_to_target and target_to_source are inverted, can be?

**Comment by rusty1s** [comment] 2019-06-05 05:13
No, you need to use the default flag for `knn`, which is `source_to_target` (the one that matches the one of the message passing layer).

**Comment by dhorka** [comment] 2019-06-05 05:29
Oh I see, then I misunderstood something. If the default value is source_to_target, at this moment the default behaviour of knn is different than the previous knn, right?

**Comment by rusty1s** [comment] 2019-06-05 05:30
Yes, but it makes more sense this way and should prevent a lot of mistakes.

**Comment by dhorka** [comment] 2019-06-05 05:34
Ok, now I understand.

 I am trying to check to check if the pooling layers are obtaining the same results, but I have problems to recover the positions of the node of the original implementation..

**Comment by rusty1s** [comment] 2019-06-05 05:37
Well, you can compare the `mean` or `sum` of positions/features in the node dimension. Alternatively, you can use something like sorting, *e.g.*,
```python
idx = pos[:, 0] + 100 * pos[:, 1] + 10000 * pos[:, 2]
_, perm = idx.sort()
pos = pos[perm]
x = x[perm]
```
both for ecc and pyg positions/features separately.

**Comment by dhorka** [comment] 2019-06-05 05:40
I will do the first one, you are right using the sum should be a good method to compare both outputs.
I was wondering, are these changes also applied to the radius graph generator?

**Comment by rusty1s** [comment] 2019-06-05 05:41
Yes, but it is not needed there, because the radius graph generation results in a symmetric adjacency matrix.

**Comment by dhorka** [comment] 2019-06-05 05:52
After checking the ouputs of max_pooling of both implementation, I see that there are difference. 

ecc features conv1:  (993, 16)
pygeometric features conv1:  (993, 16)
Max difference between features of conv1 4.7683716e-07
ecc features conv2:  (993, 32)
pygeometric features conv2:  (993, 32)
Max difference between features of conv2 3.5762787e-07
Output of ecc pooling:  (257, 32)
Output of PyGeometric pooling:  torch.Size([257, 32])
Sum max_pool ecc 2773.065 # sum of all features of the output of max pooling ecc
Sum max_pool pygeometric 1158.84 # sum of all the features of the output of max pooling pyg
Max difference between features of max_pool1 1614.225 # difference

As you can see there is a huge difference between the output of the max_pool layers. In contrast the first both convs are obtaining similar results.

**Comment by rusty1s** [comment] 2019-06-05 05:55
Can you do this for the point positions as well?

**Comment by dhorka** [comment] 2019-06-05 05:56
I was trying to do it, but I have troubles to recover the point positions of the ecc... I am not sure where are storing this information in the original implementation.

**Comment by rusty1s** [comment] 2019-06-05 05:56
Ah, I see. Ok, I will look into it.

**Comment by dhorka** [comment] 2019-06-05 07:30
I managed to recover the positions of ecc implementation. They were lost on this [method](https://github.com/dhorka/eccvspygeometric/blob/b5fa1c39641416c9aa4de91b788d865e2729c059/pointcloud_utils.py#L108). These are the results:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
ecc features conv1:  (993, 16)                                                                                                                                                                                                                                                      
pygeometric features conv1:  (993, 16)                                                                                                                                                                                                                                              
Max difference between features of conv1 4.7683716e-07                                                                                                                                                                                                                              
ecc features conv2:  (993, 32)                                                                                                                                                                                                                                                      
pygeometric features conv2:  (993, 32)                                                                                                                                                                                                                                              
Max difference between features of conv2 2.3841858e-07                                                                                                                                                                                                                              
**Output of ecc pooling:  (257, 32)                                                                                                                                                                                                                                                   
Output of PyGeometric pooling:  torch.Size([257, 32])                                                                                                                                                                                                                               
Sum max_pool ecc 2773.065                                                                                                                                                                                                                                                           
Sum max_pool pygeometric 1158.84                                                                                                                                                                                                                                                    
Difference between features of max_pool1 1614.225                                                                                                                                                                                                                                   
Size positions ecc:  (257, 3)                                                                                                                                                                                                                                                       
Size positions pyg:  (257, 3)                                                                                                                                                                                                                                                       
Sum positions ecc:  7565.66983967046                                                                                                                                                                                                                                                
Sum positions pyg:  7565.66983967046
Difference positions:  0.0** 

I will push the new code that I used to obtain these results.

**Comment by rusty1s** [comment] 2019-06-05 07:34
Interesting, thank you very much. So the error obviously lies in max pooling node features, but why? :(

**Comment by dhorka** [comment] 2019-06-05 07:39
I do not know :( I am cleaning a little bit the code(there are a lot of prints xD) before push it. I will try during the morning to change this max pool layer to an average pool and check if we have the same behavior. I will notify you when I push the code.

**Comment by rusty1s** [comment] 2019-06-05 07:40
This is for CPU only? It might be good to test both, CPU and GPU.

**Comment by dhorka** [comment] 2019-06-05 07:42
I'm testing on GPU. ECC in CPU is very slow.

**Comment by dhorka** [comment] 2019-06-05 07:53
Confirmed, in avg_pool I obtaining the same behavior using GPU:

Sum avg_pool ecc 2975.3457
Sum avg_pool pygeometric 1664.9924
Difference between features of avg_pool1 1310.3533
Size positions ecc:  (398, 3)
Size positions pyg:  (398, 3)
Sum positions ecc:  16834.863076248243
Sum positions pyg:  16834.863076248246
Difference positions:  -3.637978807091713e-12

Maybe it is related with the flow? I am not sure if the max and avg operation are affected with the flow  direction

**Comment by rusty1s** [comment] 2019-06-05 08:13
Interesting, I look into this in a minute.

**Comment by dhorka** [comment] 2019-06-05 08:58
Sorry for the delay, I had problems to push the code to git I do not know why :( [Here](https://github.com/dhorka/eccvspygeometric) you can find the code updated.

**Comment by rusty1s** [comment] 2019-06-05 09:26
Thank you. For me personally, node features are not the same when using `avg_pool` and `AGGR_MEAN` respectively.

**Comment by dhorka** [comment] 2019-06-05 09:27
What do you mean of using avg_pool and AGGR_MEAN?

**Comment by rusty1s** [comment] 2019-06-05 09:29
I sorry, I misread your previous comment.

**Comment by rusty1s** [comment] 2019-06-05 09:29
This seems like a bug in the ECC implementation.

**Comment by dhorka** [comment] 2019-06-05 09:34
If we are sure about that, for my side that it is all. =)

**Comment by rusty1s** [comment] 2019-06-05 09:37
Mh, cluster indices seems to be still different.

**Comment by dhorka** [comment] 2019-06-05 09:38
Uhmm, positions are correct and indices are wrong?

**Comment by rusty1s** [comment] 2019-06-05 09:40
Exactly.

**Comment by rusty1s** [comment] 2019-06-05 09:42
Ah! Yes, the pooling map in `ecc` is obtained by a nearest neighbor of the coarsened positions, not based on voxel affiliation.

**Comment by dhorka** [comment] 2019-06-05 09:44
We can add a flag in order to be able to choose between both algorithms?

**Comment by rusty1s** [comment] 2019-06-05 09:50
```python
from torch_geometric.nn.pool.consecutive import consecutive_cluster
from torch_geometric.utils import scatter_
from torch_cluster import nearest
```

```python
        cluster = voxel_grid(
            data.pos,
            data.batch,
            self.pool_rad,
            start=data.pos.min(dim=0)[0] - self.pool_rad * 0.5,
            end=data.pos.max(dim=0)[0] + self.pool_rad * 0.5)

        cluster, perm = consecutive_cluster(cluster)
        new_pos = scatter_('mean', data.pos, cluster)
        cluster = nearest(data.pos, new_pos, data.batch, data.batch[perm])
        data.x = scatter_('max', data.x, cluster)
        data.pos = new_pos
        return data
```
This computes new node features like it is done in the `ecc` implementation.

**Comment by rusty1s** [comment] 2019-06-05 09:54
We can not simply add a flag to `max_pool` to achieve this. We need to add our own implementation of this operator, or simply let users define this implementation on their own.

**Comment by dhorka** [comment] 2019-06-05 09:56
Thanks! I will check it!

**Comment by dhorka** [comment] 2019-06-05 11:33
These are the reuslts after check:

ecc features conv1:  (993, 16)
pygeometric features conv1:  (993, 16)
Max difference between features of conv1 7.1525574e-07
ecc features conv2:  (993, 32)
pygeometric features conv2:  (993, 32)
Max difference between features of conv2 2.3841858e-07
**Output of ecc pooling:  (257, 32)
Output of PyGeometric pooling:  torch.Size([28, 32])**
Sum max_pool ecc 2773.065
Sum max_pool pygeometric 328.0657
**Difference between features of max_pool1 2444.9993**
Size positions ecc:  (257, 3)
Size positions pyg:  (28, 3)
Sum positions ecc:  7565.66983967046
Sum positions pyg:  841.835113007279
**Difference positions:  6723.834726663181**

It seems like is not achieving the same results, right? The code used as a max_pool is this one:

> class GraphMaxPooling(torch.nn.Module):
>       def __init__(self, pool_rad):
>           super(GraphMaxPooling, self).__init__()
>           self.pool_rad = pool_rad
>           self.graph = T.Compose([T.KNNGraph(9, loop=True), T.Cartesian(norm=False, cat=True)])
>   
>       def forward(self, data):
>           cluster = voxel_grid(data.pos, data.batch, self.pool_rad,
>                               start=data.pos.min(dim=0)[0] - self.pool_rad * 0.5,
>                               end=data.pos.max(dim=0)[0] + self.pool_rad * 0.5)
>   
>           cluster, perm = consecutive_cluster(cluster)
>  
>           new_pos = scatter_('mean', data.pos, cluster)
>           new_batch = data.batch[perm]
>   
>           cluster = nearest(data.pos, new_pos, data.batch, new_batch)
>           data.x = scatter_('max', data.x, cluster)
>   
>           data.pos = new_pos
>           data.batch = new_batch
>           data.edge_attr = None
>   
>           data = self.graph(data)
>           return data
>

**Comment by rusty1s** [comment] 2019-06-05 11:41
```
ECC Weights and PyGeometric weights are equal: True
Loading weights
Starting validation:
ecc features conv1:  (997, 16)
pygeometric features conv1:  (997, 16)
Max difference between features of conv1 4.7683716e-07
ecc features conv2:  (997, 32)
pygeometric features conv2:  (997, 32)
Max difference between features of conv2 3.5762787e-07
Output of ecc pooling:  (398, 32)
Output of PyGeometric pooling:  torch.Size([47, 32])
Sum max_pool ecc 4054.4414
Sum max_pool pygeometric 509.8744
Difference between features of max_pool1 3544.567
Size positions ecc:  (398, 3)
Size positions pyg:  (47, 3)
Sum positions ecc:  16834.863076248246
Sum positions pyg:  1998.5325911267726
Difference positions:  14836.330485121474
Pygeomtric Acc:  63.65638766519823  Ecc accuracy:  63.65638766519823
Pygeomtric Loss:  0.9878960048312128  Ecc Loss:  0.9878960125771908
```

**Comment by rusty1s** [comment] 2019-06-05 11:42
I'm not sure if the print statements are buggy, but accuracy and loss are the same for me.

**Comment by dhorka** [comment] 2019-06-05 11:58
You are right, prints are buggy. The hook it's taking the value of the last max_pooling I do not know why. Thank you very much!

I would like to ask if you can explain me this better. 

> Ah! Yes, the pooling map in ecc is obtained by a nearest neighbor search on the coarsened positions, not based on voxel affiliation like in PyG.

I don't see the difference.  When you are talking about voxel affiliation you mean all the pixels that are inside the voxel, right? With these points are estimated the new features and new positions, right? It is not the same that say that you are using the nearest neighbors?

Thanks,

**Comment by rusty1s** [comment] 2019-06-05 12:04
Not necessarily, imagine two neighboring voxels with two resulting mean superpoints marked as `x` (the resulting coarsened points) and an outlier `o`:
```
+-----+-----+
|x    |     |
|    o|x    |
+-----+-----+
```
PyG `max_pool` pools the `o` in the left voxel, whereas `ecc` pools the `o` into the right voxel (because it is nearer to the superpoint in the right voxel.

**Comment by dhorka** [comment] 2019-06-05 12:07
Oh I see!! Then for each point you find the nearest "superpoint" right?

**Comment by rusty1s** [comment] 2019-06-05 12:08
Yes, we basically create a new cluster based on superpoint positions and initial point cloud.

**Comment by dhorka** [comment] 2019-06-05 12:11
Then if I understood properly the whole process is:

You create the voxels using the voxel_grid. After that you estimate the "super point" for each voxel and then for each point you assign the nearest super point. Right?

What I am missing at this moment is the purpose of this function `consecutive_cluster(cluster)` .

**Comment by rusty1s** [comment] 2019-06-05 12:14
Yes. The `voxel_grid` method creates non-consecutive cluster ids, *e.g.*, `[1, 5, 1, 5, 10]`. The `consecutive_cluster` method redefines cluster ids to `[0, 1, 0, 1, 2]` so we can use basic scatter ops for pooling and coarsening.

**Comment by dhorka** [comment] 2019-06-05 12:21
And the perm variable what is its value? Because `consecutive_cluster` is returning two values.

**Comment by rusty1s** [comment] 2019-06-05 12:25
It has quite a strange name :D It holds one original `idx` for each cluster id and is therefore used for filtering the batch indices.

**Comment by dhorka** [comment] 2019-06-05 12:43
I see, thanks!! I think we can close the issue =D  One last question, can I find the last version of torch_cluster and torch_geometric in pip repositories?

**Comment by rusty1s** [comment] 2019-06-05 12:44
Cool :) `torch-cluster` is released in PyPi, and PyG will follow soon.

**Closed by rusty1s** 2019-06-05 12:44 UTC

**Comment by dhorka** [comment] 2019-06-06 04:51
Hi,
I put here this problem because I am not sure if it is related or not. All the things that we are done here was working perfectly on the test that I provided. However in train phase I get this error after 30 epochs:

```
  File "/home/venv/graph/lib/python3.6/site-packages/torch_geometric-1.3.0-py3.6.egg/torch_geometric/nn/glob/glob.py", line 47, in global_mean_pool                                                                                                          
    # Patterns ending with a slash should match only directories
  File "/home/venv/graph/lib/python3.6/site-packages/torch_geometric-1.3.0-py3.6.egg/torch_geometric/utils/scatter.py", line 28, in scatter_                                                                                                                 
  File "/home/venv/graph/lib/python3.6/site-packages/torch_scatter/mean.py", line 68, in scatter_mean
    out = scatter_add(src, index, dim, out, dim_size, fill_value)
  File "/home/venv/graph/lib/python3.6/site-packages/torch_scatter/add.py", line 72, in scatter_add
    src, out, index, dim = gen(src, index, dim, out, dim_size, fill_value)
  File "/home/venv/graph/lib/python3.6/site-packages/torch_scatter/utils/gen.py", line 17, in gen
    index = index.view(index_size).expand_as(src)
RuntimeError: shape '[5543, 1]' is invalid for input of size 5544
srun: error: gpic10: task 0: Exited with exit code 1
=====================================================
```
In the training phase I am doing data augmentation, in this data augmentation I am doing a dropout of points, that means in each epoch there are different graphs of different sizes, also, in the same batch there are different sizes of graphs. I am not getting this error if I use the max_pool provided in PyG, moreover the error is trigerred in the global_mean_pool... that seems weird to me.. Do you have any clue that what can be happenning?

**Comment by rusty1s** [comment] 2019-06-06 05:26
Try adding the `size` argument to the [`global_mean_pool`](https://rusty1s.github.io/pytorch_geometric/build/html/modules/nn.html?highlight=global_mean_pool#torch_geometric.nn.glob.global_mean_pool) op.

**Comment by dhorka** [comment] 2019-06-06 06:18
I tried but.. it does not solve the issue.

**Comment by dhorka** [comment] 2019-06-06 06:21
Moreover, I executed an experiment that uses max_pool + cluster with the new start and end and global_mean_pool is working properly. I think the issue is related to the code new code used to calculate the max_pool.

**Comment by rusty1s** [comment] 2019-06-06 06:24
```python
data.x = scatter_('max', data.x, cluster, dim_size=new_pos.size(0))
```

**Comment by dhorka** [comment] 2019-06-06 08:53
Oh I see, thats solves the problem. But I do not understand why..

**Comment by rusty1s** [comment] 2019-06-06 08:55
It seems that in rare cases, newly computed clusters via nearest neighbor result in a different amount of clusters produced, e.g., there can be empty clusters, hence new_x and new_pos have different shape.

**Comment by dhorka** [comment] 2019-06-06 09:19
> It seems that in rare cases, newly computed clusters via nearest neighbor result in a different amount of clusters produced, e.g., there can be empty clusters, hence new_x and new_pos have a different shape.
We can know which cluster is empty? I mean, it should be better to suppress the empty cluster. Is it always the last one?

**Comment by rusty1s** [comment] 2019-06-06 09:21
No its not, that's just the case when it crashes. You cannot suppress empty clusters, because officially they are there (they have a point in space), just with a zero representation.

**Comment by dhorka** [comment] 2019-06-06 09:24
But, if any previous node is assigned to this cluster (using the nearest algorithm I mean), this new point doesn't have any feature and I think it is not interesting to have this node on my graph. How can I know which node has no representation? Because far as I understood the dim_size is adding 0 padding to the end of the feature vector, right?

**Comment by rusty1s** [comment] 2019-06-06 09:27
I guess you need to recompute `pos_new` and `batch_new` (untested):
```python
cluster = nearest(data.pos, new_pos, data.batch, new_batch)
data.x = scatter_('max', data.x, cluster)
data.pos = scatter_('mean', data.pos, cluster)
data.batch = torch.scatter(0, cluster, data.batch) 
```

**Comment by dhorka** [comment] 2019-06-06 09:42
The calculation of new data.batch it is not working:

TypeError: scatter() received an invalid combination of arguments - got (int, Tensor, Tensor), but expected one of:
 * (Tensor input, int dim, Tensor index, Tensor src)
 * (Tensor input, int dim, Tensor index, Number value)

**Comment by rusty1s** [comment] 2019-06-06 09:44
```python
data.batch.new_empty(data.pos.size(0).scatter_(0, cluster, data.batch)
```
should do the trick.

**Comment by dhorka** [comment] 2019-06-06 09:54
```
cluster size:,  torch.Size([993])
new batch size:  torch.Size([993])
x size:  torch.Size([257, 32])
new pos size:  torch.Size([257, 3])
```
These are the outputs of the size of each tensor. As you can see new_batch is not properly generated ..
It is due to the fact that cluster size is 993.

**Comment by rusty1s** [comment] 2019-06-06 09:55
The new `data.batch` has the shape of `data.pos.size(0)`, which should be `257`.

**Comment by dhorka** [comment] 2019-06-06 09:58
```
def forward(self, data):
        cluster = voxel_grid(data.pos, data.batch, self.pool_rad, 
                            start=data.pos.min(dim=0)[0] - self.pool_rad * 0.5, 
                            end=data.pos.max(dim=0)[0] + self.pool_rad * 0.5)
    
        cluster, perm = consecutive_cluster(cluster)
    
        new_pos = scatter_('mean', data.pos, cluster)
        new_batch = data.batch[perm]
    
        cluster = nearest(data.pos, new_pos, data.batch, new_batch)
        data.x = scatter_('max', data.x, cluster)
        data.pos = scatter_('mean', data.pos, cluster)
        data.batch.new_empty(data.pos.size(0)).scatter_(0, cluster, data.batch)                                                                                                                                                                                                     
    
        print("cluster size:, ", cluster.size())
        print("new batch size: ",data.batch.size())
        print(" x size: ",data.x.size())
        print(" new pos size: ",data.pos.size())
        #data.pos = new_pos
        #data.batch = new_batch
        data.edge_attr = None
    
        #data.edge_attr = None
        #data = max_pool(cluster, data)
        data = self.graph(data)
        return data
```
This is the code that I am using, but I got a new batch with size 993

**Comment by rusty1s** [comment] 2019-06-06 09:59
`data.batch = data.batch.new_empty(data.pos.size(0)).scatter_(0, cluster, data.batch)` :D

**Comment by dhorka** [comment] 2019-06-06 10:05
Oh! you are complety right xDD After that I was getting this error:
`RuntimeError: invalid argument 3: Index tensor must not have larger size than input tensor, but got index [993] input [257]`

I modified the code:
data.batch = data.batch.new_empty(data.pos.size(0)).scatter_(0, torch.unique(cluster), data.batch)

And then seems to work. But I get this error with radius_graph:

```
row, col = radius(x, x, r, batch, batch, max_num_neighbors + 1)
  File "/work/test_modelnet_ecc_pygeometric/env/pytorch11_geometric/lib/python3.6/site-packages/torch_cluster-1.4.2-py3.6-linux-x86_64.egg/torch_cluster/radius.py", line 61, in radius                                                                 
    max_num_neighbors)
RuntimeError: scan failed to synchronize: device-side assert triggered
```

**Comment by rusty1s** [comment] 2019-06-06 10:08
No, you shouldn't use a `unique` call there. I do not understand the error though, because before calling `scatter_`, `data.batch` and `cluster` should have equal shape.

**Comment by dhorka** [comment] 2019-06-06 10:17
Sorry, it was a mistake in my code I found it. Now I do not need the torch.unique.  But I am obtaining this error:
```

 File "work/test_modelnet_ecc_pygeometric/env/pytorch11_geometric/lib/python3.6/site-packages/torch_cluster-1.4.2-py3.6-linux-x86_64.egg/torch_cluster/knn.py", line 113, in knn_graph
    row, col = knn(x, x, k if loop else k + 1, batch, batch)
  File "/work/test_modelnet_ecc_pygeometric/env/pytorch11_geometric/lib/python3.6/site-packages/torch_cluster-1.4.2-py3.6-linux-x86_64.egg/torch_cluster/knn.py", line 57, in knn
    return torch_cluster.knn_cuda.knn(x, y, k, batch_x, batch_y)
RuntimeError: scan failed to synchronize: device-side assert triggered

The code used:

ef forward(self, data):
        cluster = voxel_grid(data.pos, data.batch, self.pool_rad, 
                            start=data.pos.min(dim=0)[0] - self.pool_rad * 0.5, 
                            end=data.pos.max(dim=0)[0] + self.pool_rad * 0.5)                                                                                                                                                                                                       
    
        cluster, perm = consecutive_cluster(cluster)
    
        new_pos = scatter_('mean', data.pos, cluster)
        new_batch = data.batch[perm]
    
        cluster = nearest(data.pos, new_pos, data.batch, new_batch)
        data.x = scatter_('max', data.x, cluster)
        data.pos = scatter_('mean', data.pos, cluster)
        data.batch = data.batch.new_empty(data.pos.size(0)).scatter_(0, cluster, data.batch)
    
        print("cluster size:, ", cluster.size())
        print("new batch size: ",data.batch.size())
        print(" x size: ",data.x.size())
        print(" new pos size: ",data.pos.size())
        #data.pos = new_pos
        #data.batch = new_batch
        data.edge_attr = None
    
        #data.edge_attr = None
        #data = max_pool(cluster, data)
        data = self.graph(data)
        return data

```

**Comment by rusty1s** [comment] 2019-06-06 10:28
Makes sense, you sadly need to call `consecutive_cluster` a second time :(
```
        cluster = voxel_grid(
            data.pos,
            data.batch,
            self.pool_rad,
            start=data.pos.min(dim=0)[0] - self.pool_rad * 0.5,
            end=data.pos.max(dim=0)[0] + self.pool_rad * 0.5)

        cluster, perm = consecutive_cluster(cluster)
        new_pos = scatter_('mean', data.pos, cluster)
        new_batch = data.batch[perm]

        cluster = nearest(data.pos, new_pos, data.batch, new_batch)
        cluster, perm = consecutive_cluster(cluster)
        data.x = scatter_('max', data.x, cluster)
        data.pos = scatter_('mean', data.pos, cluster)
        data.batch = data.batch[perm]

```

**Comment by dhorka** [comment] 2019-06-06 10:45
Hmmm, I think  I am not understanding properly the consecutive_cluster function. The thing is, Why is it not the same put the consecutive_cluster between:
```
cluster = nearest(data.pos, new_pos, data.batch, new_batch)
**cluster, perm = consecutive_cluster(cluster)**
data.x = scatter_('max', data.x, cluster)
cluster, perm = consecutive_cluster(cluster)
data.pos = scatter_('mean', data.pos, cluster)
data.batch = data.batch[perm]
```

I asking that because I was thinking to do only this extra calculation in case of d`ata.x.size(0) != new_pos.size(0)`

**Comment by rusty1s** [comment] 2019-06-06 12:16
Mh, that doesn‘t make sense. Either recompute node positions based on cluster assignment, or allow zero feature representations for nodes. The thing is, the size mismatch is not a good condition for detecting empty clusters, because it does only detect a single empty cluster (the one at the end), and nothing else.

**Comment by justanhduc** [comment] 2020-03-03 14:36
@dhorka @rusty1s could you please send me the script to reproduce ecc by torch_geometric?
